[FIREBASE_KEY]
type = "service_account"
project_id = "face-detection-20240930"
private_key_id = "c76400dcc087cc265eb423e0d6a1a40cdeccdcf5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD0+YRVdrIq6RND
W8KJEHKpgoxbHXL7rKOVYuzYn6MC+hmO+mmBrHuYWEWY7gLWLxtknvrX77yVb7jz
F5Mts75EGWB8VuoSW4PVLHamIPmU3gXIyek6SEls/BP2jlsbixR2n4weJrwcdUHh
bOB3oVQSTN3HBLfbkfJXQvMk+KZTrEcXLmH8eFm+yTcY0UsJEuPzr1e6UIac5q9a
Fni5t67r33Q86xULXFTn4SCLLRqYyNgOqfwMfUo2+KCzTk323ejtEdHHp6QRi2C8
6Pnfq6xC9SKJHHwT3prTnNj/ET3YR0JKyMFi79CPUyoz9lClQ/TILdPJswFJkwJU
mXFx7YjrAgMBAAECggEAA8w6ePi2GmQyoECz61wN6wLTGjaCqdQrVQ2LjnArHsix
zL2lFRWPdPUpXw2RjbB9RDoSuXZF/isVOu+KoJLAyF18WXEff9lbWdqunDS2qdAn
Vs2KiBTGzqG5zYC3eN3XG1+t1GnVULugodYGRNSDcSUv6v3vu7+vehrXmiMgsPta
+uvlXY8Dhp6VyfXgr0k5JSOG1YLuG7t55ECM3wdHs7lP7N1TXMugaC7fLp7kEohX
zUGF/BnT624YFxlNWHpbyw9P9vl1/XiPfIh3MB92MAXQ9zoL89azcbqxLU35Qzsf
FGdcYPiKMedKKoYvCon8Prd1KXx6m0hGXU69J9XpgQKBgQD8+jqMbEapriOOEBko
08/pTI3NOBibXcQouK//YIL4xpW9FvK0Xit1YHApQsV9Bo0mWLjx6033KwiuUR7J
d6MrWNrGNUETiE1JbA8NGQLr10PeFPd93MpfRwx4dMd5qgDkl0KOTKkb5PZRk+VO
Ydt6sGtvB3apzybBQNPX2GERcwKBgQD35s96fPLtIkHHIgAIt831BLGsg8ooDluQ
xxWPoLoSHPgqgV8fo13srewWJp9gvXeUFFkKum3Osryqhh5Fj24S5A/74KfVVzbL
cyGN4zhLox/ibVaV7dfw26XRbEQUgdTm5EuLskPkbYQiwDrx9IkJCLdWaSEbEODA
rbLWbnHsqQKBgQCRaahT5T0s9ar8UuaTYEVHXji4OMF0NQ63NYn86lX+d+/EdDdo
VCT44Ek4fmgUeLqTyzXr4Qy8waDIylo/BiTlmrqOajgQ6S07wgBY0AKs29zn//dP
AqXU5HsXllC+72h5/TRFpW0jWpX3yGJrjrZhLJ1kgc7Exw0I0qGylW8eXwKBgF1y
I8OIVgoNX74wktK2dmxl2JOvGgT/ZISuhvIdJAav5Nwg6DqE2mLdLKEs7ecJhInN
IcNpgvrnZTbiV4bhCh0U2vGXPayts3n9bCiP/iiE1QAFNx5NCZlBMsA+j2srhZWD
ePavu+ffYG+5Bn8uLnm5T2LDPjd1pUL8Nu2dtFQBAoGAXnrs1ThHeNTy8rjUKDEZ
eMrTLVAylyIGp84GYgufYxcTLObecS2qL7GD4egoBYU6vkqbs2KLixtk7VtER1pb
NbJDnMQ+0iykzm2geIwBv/wuWa5lrexHRJ6HU/F5uarnMdzuvXOfcSbFGsnzY4VK
5+Xd4DiNZ0gHqMvFfM1oKRU=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-a7zed@face-detection-20240930.iam.gserviceaccount.com"
client_id = "117567264653881093813"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-a7zed%40face-detection-20240930.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
